---
- hosts: headnode:computes
  vars_files:
  - vars.yml
  roles:
  - "universal_config"
  - "optional_tools"
  - "lmod"
  - "slurm"

# Run roles specific to the cluster headnode
- hosts: headnode
  become: true
  vars_files:
  - vars.yml
  roles:
  - "server_setup"

# Run roles specific to the cluster compute nodes
- hosts: computes
  become: true
  vars_files:
  - vars.yml
  roles:
  - "client_setup"
