---
- name: ensure nfs-related packages are installed
  apt: name={{item}} state=present
  with_items:
  - nfs-kernel-server
  - nfs4-acl-tools

- name: configure exports
  become: true
  template: src=exports dest=/etc/exports
  notify:
  - exportfs

- name: configure nfs over RDMA
  become: true
  ansible.builtin.shell: modprobe svcrdma
  when: nfs_rdma_enabled

- name: ensure nfs is running
  service: name=nfs-kernel-server state=started enabled=yes

- name: configure nfs over RDMA
  become: true
  ansible.builtin.shell: echo rdma 20049 > /proc/fs/nfsd/portlist
  when: nfs_rdma_enabled
  notify:
    - restart nfs
