---
- name: Make '{{ default_shell }}' the default shell
  become: true
  ansible.builtin.shell: usermod -s {{ default_shell }} {{ ansible_user }}


- name: apt-add universe
  become: true
  ansible.builtin.shell: apt-add-repository universe

- name: Upgrade all apt packages
  become: true
  apt: update_cache=yes upgrade=dist force_apt_get=yes

- name: Install the package "bash_completion"
  become: true
  apt:
    name: bash-completion
    state: present

- name: Install the package "command not found"
  become: true
  apt:
    name: command-not-found
    state: present

- name: Install the package rdma-core
  become: true
  apt:
    name: rdma-core
    state: present

- name: Install the package librdmacm-dev
  become: true
  apt:
    name: librdmacm-dev
    state: present

- name: install OpenMPI packages
  become: true
  apt: name={{ item }} state=present
  with_items:
  - libopenmpi-dev  # consider also installing mpi4py and boost
  - openmpi-bin
  - openmpi-common
  - libgtk2.0-dev

- name: download and unarchive openmpi
  become: true
  ansible.builtin.unarchive:
    src: 'https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-{{ ompi_version }}.tar.gz'
    dest: /opt
    remote_src: yes

- name: install openmpi
  become: true
  ansible.builtin.shell: ./configure --prefix='/opt/openMPI/{{ ompi_version }}' --enable-orterun-prefix-by-default; make -j 16; make install -j 16
  args:
    chdir: /opt/openmpi-{{ ompi_version }}

- name: Generate ssh key to communicate to other machines for mpi
  community.crypto.openssh_keypair:
    path: '{{ ansible_env.HOME }}/.ssh/id_rsa'
    type: rsa

- name: copy key to authorized_keys
  ansible.builtin.shell: cat '{{ ansible_env.HOME }}/.ssh/id_rsa.pub' >> '{{ ansible_env.HOME }}/.ssh/authorized_keys'

- name: create /opt/hpctools
  become: true
  ansible.builtin.file:
    path: /opt/hpctools
    state: directory
    mode: '0755'
