---
- name: apt-add universe
  become: true
  ansible.builtin.shell: apt-add-repository universe

- name: Upgrade all apt packages
  become: true
  apt: update_cache=yes upgrade=dist force_apt_get=yes

- name: Install the package "bash_completion"
  become: true
  apt:
    name: bash-completion
    state: present

- name: Install the package "command not found"
  become: true
  apt:
    name: command-not-found
    state: present

- name: Install the package rdma-core
  become: true
  apt:
    name: rdma-core
    state: present

- name: Install the package librdmacm-dev
  become: true
  apt:
    name: librdmacm-dev
    state: present

- name: install OpenMPI packages
  apt: name={{ item }} state=present
  with_items:
  - libopenmpi-dev  # consider also installing mpi4py and boost
  - openmpi-bin
  - openmpi-common
  - libgtk2.0-dev

- name: Install mpich
  become: true
  apt:
    name: mpich
    state: present

#- name: Install libpmi
#  become: true
#  apt:
#    name: name={{ item }} state=present
#    state: present
#  with_items:
#    - libpmi-pmix-dev
    #- libpmi2-0-dev

- name: Generate ssh key to communicate to other machines for mpi
  community.crypto.openssh_keypair:
    path: "{{ ansible_env.HOME }}/.ssh/id_rsa"
    type: rsa

- name: copy key to authorized_keys
  ansible.builtin.shell: cat "{{ ansible_env.HOME }}/.ssh/id_rsa.pub" >> "{{ ansible_env.HOME }}/.ssh/authorized_keys"
